package com.juanfbenitez.prueba.idealista.ui.detail

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.juanfbenitez.prueba.idealista.data.api.model.PropertyDetailDTO
import com.juanfbenitez.prueba.idealista.data.db.FavoriteEntity
import com.juanfbenitez.prueba.idealista.domain.usecase.GetAllFavoritesUseCase
import com.juanfbenitez.prueba.idealista.domain.usecase.GetPropertyDetailUseCase
import com.juanfbenitez.prueba.idealista.domain.usecase.ToggleFavoriteUseCase
import dagger.assisted.Assisted
import dagger.assisted.AssistedFactory
import dagger.assisted.AssistedInject
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

sealed class PropertyDetailUiState {
    object Loading : PropertyDetailUiState()
    data class Success(
        val detail: PropertyDetailDTO,
        val favorite: FavoriteEntity?
    ) : PropertyDetailUiState()
    data class Error(val message: String) : PropertyDetailUiState()
}

/**
 * [propertyCode] is only known at runtime (nav arg / drawer selection), so this ViewModel is
 * created via assisted injection: [Factory] is generated by Hilt and can be obtained through
 * constructor injection (Fragment) or an [dagger.hilt.EntryPoint] (Compose), then used with
 * [provideFactory] to build a standard [ViewModelProvider.Factory].
 */
class PropertyDetailViewModel @AssistedInject constructor(
    private val getPropertyDetailUseCase: GetPropertyDetailUseCase,
    private val getAllFavoritesUseCase: GetAllFavoritesUseCase,
    private val toggleFavoriteUseCase: ToggleFavoriteUseCase,
    @Assisted private val propertyCode: String
) : ViewModel() {

    @AssistedFactory
    interface Factory {
        fun create(propertyCode: String): PropertyDetailViewModel
    }

    private val _detail = MutableStateFlow<PropertyDetailDTO?>(null)
    private val _uiState = MutableStateFlow<PropertyDetailUiState>(PropertyDetailUiState.Loading)
    val uiState: StateFlow<PropertyDetailUiState> = _uiState.asStateFlow()

    init {
        observeData()
        loadDetail()
    }

    private fun observeData() {
        viewModelScope.launch {
            combine(_detail, getAllFavoritesUseCase()) { detail, favorites ->
                if (detail == null) {
                    PropertyDetailUiState.Loading
                } else {
                    val favorite = favorites.find { it.propertyCode == propertyCode }
                    PropertyDetailUiState.Success(detail, favorite)
                }
            }.collect {
                _uiState.value = it
            }
        }
    }

    fun loadDetail() {
        viewModelScope.launch {
            try {
                _uiState.value = PropertyDetailUiState.Loading
                val detail = getPropertyDetailUseCase(propertyCode)
                _detail.value = detail
            } catch (e: Exception) {
                _uiState.value = PropertyDetailUiState.Error(e.message ?: "Unknown error")
            }
        }
    }

    fun toggleFavorite() {
        viewModelScope.launch {
            toggleFavoriteUseCase(propertyCode)
        }
    }

    companion object {
        fun provideFactory(
            assistedFactory: Factory,
            propertyCode: String
        ): ViewModelProvider.Factory = object : ViewModelProvider.Factory {
            @Suppress("UNCHECKED_CAST")
            override fun <T : ViewModel> create(modelClass: Class<T>): T {
                return assistedFactory.create(propertyCode) as T
            }
        }
    }
}
